#!/usr/bin/env node
/**
 * WhatWord ESDB ingestion pipeline — lexical existence import.
 *
 *   INPUT (en-wl/wordlist, v2 branch, MIT-like license)
 *     ↓ SOURCE VALIDATION (license + Copyright notice check)
 *     ↓ PARSING (scowl.db via libscowl, or scowl.txt export)
 *     ↓ NORMALISATION (lowercase, NFKC, dedupe canonical keys)
 *     ↓ VALIDATION (a-z, length 1-45, variant-level ≤ 1, NO AU codes, size ≤ 70)
 *     ↓ PROVENANCE ATTACHMENT (fieldSources.spelling = 'esdb', commit hash recorded)
 *     ↓ WORD GRAPH UPDATE (upsert words table; emits src/data/esdb-corpus.generated.ts)
 *     ↓ DERIVED INDEX GENERATION (signatures rebuilt at boot by the engine)
 *     ↓ QUALITY REPORT (DATA_QUALITY_REPORT section)
 *
 * Repeatable: running twice never creates duplicates (canonical-key upsert).
 * Definitions are NEVER imported here — enrichment is scripts/enrich-freedictionary.mjs.
 *
 * Usage:
 *   node scripts/ingest-esdb.mjs --checkout /tmp/esdb --size 60 --spellings A --emit
 *
 * Prerequisites: git checkout of https://github.com/en-wl/wordlist (branch v2),
 * built database (make), python3 + libscowl available.
 */
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const [k, v] = a.replace(/^--/, '').split('=');
    return [k, v ?? true];
  }),
);

const CHECKOUT = args.checkout || process.env.ESDB_CHECKOUT || '';
const SIZE = parseInt(args.size || '60', 10);
const SPELLINGS = args.spellings || 'A';

if (SIZE > 70) {
  console.error('[ingest-esdb] REFUSED: size > 70 pulls in UKACD-copyright material. See WORD-SOURCES.md.');
  process.exit(1);
}
if (!CHECKOUT || !existsSync(join(CHECKOUT, 'Copyright'))) {
  console.error('[ingest-esdb] Provide --checkout=<en-wl/wordlist v2 checkout> containing the Copyright file.');
  process.exit(1);
}

// 1. SOURCE VALIDATION — the permissive grant + attribution notice must be present.
const copyright = readFileSync(join(CHECKOUT, 'Copyright'), 'utf8');
if (!copyright.includes('Copyright 2000-2026 by Kevin Atkinson')) {
  console.error('[ingest-esdb] REFUSED: ESDB Copyright notice not found — licensing unclear, aborting.');
  process.exit(1);
}
let commit = 'unknown';
try {
  commit = execSync('git rev-parse HEAD', { cwd: CHECKOUT, encoding: 'utf8' }).trim();
} catch { /* non-git export; version recorded as unknown */ }
console.log(`[ingest-esdb] Source validated. ESDB commit: ${commit}`);

// 2-3. PARSING + NORMALISATION via libscowl word-list export.
const outPath = join(process.cwd(), '.tmp-esdb-wl.txt');
try {
  execSync(
    `./scowl word-list ${SIZE} ${SPELLINGS} 1 --categories= > "${outPath}"`,
    { cwd: CHECKOUT, stdio: 'inherit' },
  );
} catch (err) {
  console.error('[ingest-esdb] libscowl export failed. See en-wl/wordlist README (make, python3 required).');
  process.exit(1);
}

const raw = readFileSync(outPath, 'utf8').split('\n').map((s) => s.trim()).filter(Boolean);
const seen = new Map();
let rejected = 0;
for (const line of raw) {
  // 4. VALIDATION — plain alphabetic words only; AU/UKACD material excluded by construction.
  const canonical = line.normalize('NFKC').toLowerCase();
  if (!/^[a-z](?:[a-z'-]*[a-z])?$/.test(canonical) || canonical.length > 45) { rejected++; continue; }
  if (/--|''|-'|'-/.test(canonical)) { rejected++; continue; }
  if (!seen.has(canonical)) seen.set(canonical, line);
}

console.log(`[ingest-esdb] accepted=${seen.size} rejected=${rejected} duplicates=${raw.length - seen.size - rejected}`);

// 5-6. PROVENANCE + WORD GRAPH UPDATE — emit generated corpus module.
if (args.emit) {
  const words = [...seen.keys()].sort();
  const body = `// GENERATED by scripts/ingest-esdb.mjs — do not hand-edit.\n` +
    `// Source: en-wl/wordlist v2 @ ${commit} (size ${SIZE}, spellings ${SPELLINGS}).\n` +
    `// License: ESDB MIT-like; attribution: Copyright 2000-2026 by Kevin Atkinson.\n` +
    `export const ESDB_COMMIT = ${JSON.stringify(commit)};\n` +
    `export const ESDB_WORDS: string[] = ${JSON.stringify(words)};\n`;
  const target = join(process.cwd(), 'src', 'data', 'esdb-corpus.generated.ts');
  mkdirSync(join(process.cwd(), 'src', 'data'), { recursive: true });
  writeFileSync(target, body);
  console.log(`[ingest-esdb] wrote ${target} (${words.length} words)`);
}

// 7. QUALITY REPORT snippet.
console.log('[ingest-esdb] QUALITY: total source records=%d accepted=%d rejected=%d duplicates=%d',
  raw.length, seen.size, rejected, raw.length - seen.size - rejected);
console.log('[ingest-esdb] done. Next: scripts/enrich-freedictionary.mjs for definitions.');
